import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import MotionProvider from "@/components/MotionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Framer motion demos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex p-4 gap-4 fixed bg-gray-800 w-full">
          <li className="list-item">
            <Link href="/demo1">Demo 1</Link>
          </li>
          <li className="list-item">
            <Link href="/demo2">Demo 2</Link>
          </li>
          <li className="list-item">
            <Link href="/demo3">Demo 3</Link>
          </li>
          <li className="list-item">
            <Link href="/demo4">Demo 4</Link>
          </li>
          <li className="list-item">
            <Link href="/demo5">Demo 5</Link>
          </li>
          <li className="list-item">
            <Link href="/more-info">More info</Link>
          </li>
        </ul>

        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex"></div>

          <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:-z-10 before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px]">
            <MotionProvider>{children}</MotionProvider>
          </div>

          <div className="mb-32 grid text-center lg:mb-0 lg:grid-cols-4 lg:text-left"></div>
        </main>
      </body>
    </html>
  );
}
